### ISSUE TITLE
Create Tests for Incident Management

### ISSUE THREAD

**Issue by jacebenson** [jacebenson/x_8821_atf#17]
To get started.  

1. Spin up an instance on developer.servicenow.com (london version).
2. Comment on this issue that you want to take it.
3. Fork this project
4. Import your forked project within studio in servicenow
5. Create changes per this issue
6. Commit your app to your fork
7. From your fork, make a Pull request

The desired output is a set of tests to test the functionality of the tool in a out of box state.

Build tests to test the functionality of a part of IT Service Management.  Pick one for a PR.
[Docs](https://docs.servicenow.com/bundle/london-it-service-management/page/product/incident-management/concept/c_IncidentManagement.html)

**Comment by earlduque** [comment]
dibs

**Comment by jacebenson** [comment]
@earlduque accepted your PR for the full Incident test.  I'll have to add some more here eventually to test the oob rules and such

**Comment by mhzgitdev** [comment]
haha, I got my repo after you committed this, so I just found those tests and ran it, like, "what the heck, it seems like this one works.."

**Comment by mhzgitdev** [comment]
This gives error on London PDI:
FAILURE: Failed to set field 'assignment_group' to value '12a586cd0bb23200ecfd818393673a30' because the reference is NOT valid. The group "Incident Management" is present on Kingston but not on London.

**Comment by earlduque** [comment]
Fixed and a pull request was submitted. Made it jakarta friendly
