### ISSUE TITLE
Not an issue, only a question.

### ISSUE THREAD

**Issue by adityaraute** [jacebenson/x_8821_atf#191]
When ServiceNow adopted ATF, was this repository the core inspiration behind it? I'd be very keen to know.

**Comment by jacebenson** [comment]
This was made initially to be what quick tests became

**Comment by jacebenson** [comment]
This was made after servicenow had annouced ATF, before they started releasing quick tests

**Comment by adityaraute** [comment]
Oh okay, thanks for the clarification.
